name: Pull Request Opened
on:
  pull_request:
    branches: [main]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install NodeJS 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Code Linting
        run: npm run lint
      - name: Type Checks
        run: npm run typecheck
      - name: Unit tests
        run: npm run coverage
      - run: echo "🍏 This job's status is ${{ job.status }}."
